In [1]:
import numpy as np
import pandas as pd

***
---

# <span style = "color:blue">Numpy</span>

### Numpy array

In [4]:
a = np.array([1, 2, 3])
print(a[1])
print(a)

2
[1 2 3]


In [23]:
b = np.array([[1, 2, 3], [11, 22 ,33]])
print(b[0][2])
print(b)

c = np.arange(12).reshape(2, 2, 3)
print(c)

3
[[ 1  2  3]
 [11 22 33]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [9]:
print(b.shape) 
print(b.ndim)
print(b.dtype) # data type
print(b.itemsize) # datat type의 byte
print(b.size) # 전체 요소 개수

(2, 3)
2
int32
4
6


In [16]:
a = np.arange(12).reshape(3, 4)
b = np.arange(1, 13).reshape(3, 4)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[  0   2   6  12]
 [ 20  30  42  56]
 [ 72  90 110 132]]
[[0.         0.5        0.66666667 0.75      ]
 [0.8        0.83333333 0.85714286 0.875     ]
 [0.88888889 0.9        0.90909091 0.91666667]]


In [26]:
print(a[:2, 1:3])
print(a[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [5 6]]
[0 5 8]


In [30]:
print(c)
print()

print(c[c>=4])
print()

print(c[c%3==0])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[ 4  5  6  7  8  9 10 11]

[0 3 6 9]


***
---

# <span style='color:blue'>Pandas</sapn>

### Pandas Series

In [32]:
a = pd.Series([1, 2, 3, 4])
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [34]:
b = pd.Series([1, 2, 3, 4], index = ["a", "b", "c", "d"])
print(b)

a    1
b    2
c    3
d    4
dtype: int64


### Pandas DataFrame

In [53]:
data = {"a": ['asdf', 'qwer', 'zxcv', 'asdf', 'qwer', 'zxcv'],
       "b": ["1234", "2345", "3456", "1234", "2345", "3456"],
       "c": ["qqqq", "wwww", "eeee", "qqqq", "wwww", "eeee"],
       "d":[1, 2, 3, 11, 22 ,33],
       "e":[4, 5, 6, 44, 55 ,66]}

df = pd.DataFrame(data)
df

a     b     c   d   e
0  asdf  1234  qqqq   1   4
1  qwer  2345  wwww   2   5
2  zxcv  3456  eeee   3   6
3  asdf  1234  qqqq  11  44
4  qwer  2345  wwww  22  55
5  zxcv  3456  eeee  33  66

In [ ]:
df.columns

### <span style = 'background:yellow'>Pandas data handling<span>

#### data 가져오기

In [54]:
df.loc[1] # loc: 행의 이름 사용

a    qwer
b    2345
c    wwww
d       2
e       5
Name: 1, dtype: object

In [55]:
print(df.iloc[2]) # iloc: 행,열 사용
print()
print(df.iloc[0, 1])

a    zxcv
b    3456
c    eeee
d       3
e       6
Name: 2, dtype: object

1234


#### <span style = 'background:yellow'> 통게 분석 함수(sum, corr, mean, min, var, cov)

In [64]:
df.sum(axis = 0) # column 단위로 sum
df.mean()
df.min()
df.var()


b    2.057058e+22
d    1.200000e+01
e    3.000000e+01
dtype: float64

In [65]:
print(df["d"].corr(df["e"])) # corr 구하기
print(df["d"].cov(df["e"])) # cov 구하기

0.9498854317510009
348.8


#### 정렬 함수(sort_index, sort_values)

In [66]:
df = pd.DataFrame(data, index = ["1", "3", "2", "0", "4", "5"])

In [70]:
df.sort_index(axis = 0) # sort by index

a     b     c   d   e
0  asdf  1234  qqqq  11  44
1  asdf  1234  qqqq   1   4
2  zxcv  3456  eeee   3   6
3  qwer  2345  wwww   2   5
4  qwer  2345  wwww  22  55
5  zxcv  3456  eeee  33  66

In [72]:
df.sort_values(by = "e") # sort by column

a     b     c   d   e
1  asdf  1234  qqqq   1   4
3  qwer  2345  wwww   2   5
2  zxcv  3456  eeee   3   6
0  asdf  1234  qqqq  11  44
4  qwer  2345  wwww  22  55
5  zxcv  3456  eeee  33  66

#### boolean indexing

In [73]:
print(c[c%3==0])

[0 3 6 9]


In [92]:
qr = np.random.randint(1, 10, (6, 4))
qr = pd.DataFrame(qr, index = ["b", "c", "e", "d", "a", "f"])
qr = qr.sort_index()

qr

0  1  2  3
a  3  4  9  5
b  8  2  4  1
c  1  4  6  8
d  2  3  8  7
e  2  6  1  8
f  2  6  2  1

In [94]:
qr[qr[0]>=3]

0  1  2  3
a  3  4  9  5
b  8  2  4  1

## <span style = 'background:yellow'>Query Function

In [108]:
qr = qr.rename(columns={0:"a", 1:"b", 2:"c", 3:"d"}) # 이름 바꾸기
qr

a  b  c  d
a  3  4  9  5
b  8  2  4  1
c  1  4  6  8
d  2  3  8  7
e  2  6  1  8
f  2  6  2  1

In [113]:
qr.query("a >= 2")

a  b  c  d
a  3  4  9  5
b  8  2  4  1
d  2  3  8  7
e  2  6  1  8
f  2  6  2  1

In [116]:
n = 2
p = 4
qr.query("a >= @n & b >= @p") # 외부 변수 참조 시 앞에 @ 사용@ 사용

a  b  c  d
a  3  4  9  5
e  2  6  1  8
f  2  6  2  1

In [134]:
sales = pd.read_csv("Pandas-Data-Science-Tasks-master/SalesAnalysis/Sales_Data/Sales_September_2019.csv")
sales = df[0:100]

sales

Order ID                   Product Quantity Ordered Price Each  \
0    248151     AA Batteries (4-pack)                4       3.84   
1    248152      USB-C Charging Cable                2      11.95   
2    248153      USB-C Charging Cable                1      11.95   
3    248154          27in FHD Monitor                1     149.99   
4    248155      USB-C Charging Cable                1      11.95   
..      ...                       ...              ...        ...   
95   248243      USB-C Charging Cable                1      11.95   
96   248244  Lightning Charging Cable                1      14.95   
97   248245          Wired Headphones                1      11.99   
98   248246          Wired Headphones                1      11.99   
99   248247    27in 4K Gaming Monitor                1     389.99   

        Order Date                       Purchase Address  
0   09/17/19 14:44    380 North St, Los Angeles, CA 90001  
1   09/29/19 10:19           511 8th St, Austin, TX 73301  
2   09/16/19 17:48  151 Johnson St, Los Angeles, CA 90001  
3   09/27/19 07:52      355 Hickory St, Seattle, WA 98101  
4   09/01/19 19:03          125 5th St, Atlanta, GA 30301  
..             ...                                    ...  
95  09/04/19 10:49   522 12th St, San Francisco, CA 94016  
96  09/21/19 16:01         57 Willow St, Dallas, TX 75001  
97  09/15/19 10:40         969 Maple St, Dallas, TX 75001  
98  09/11/19 20:13   727 Center St, Los Angeles, CA 90001  
99  09/09/19 23:35    192 7th St, New York City, NY 10001  

[100 rows x 6 columns]

In [133]:
sales.groupby(["Product"]).count()


Order ID  Quantity Ordered  Price Each  \
Product                                                              
20in Monitor                       3                 3           3   
27in 4K Gaming Monitor             2                 2           2   
27in FHD Monitor                   4                 4           4   
34in Ultrawide Monitor             5                 5           5   
AA Batteries (4-pack)              9                 9           9   
AAA Batteries (4-pack)            11                11          11   
Apple Airpods Headphones          10                10          10   
Bose SoundSport Headphones         4                 4           4   
Flatscreen TV                      2                 2           2   
Google Phone                       4                 4           4   
Lightning Charging Cable          17                17          17   
Macbook Pro Laptop                 2                 2           2   
ThinkPad Laptop                    1                 1           1   
USB-C Charging Cable              14                14          14   
Vareebadd Phone                    1                 1           1   
Wired Headphones                   9                 9           9   
iPhone                             2                 2           2   

                            Order Date  Purchase Address  
Product                                                   
20in Monitor                         3                 3  
27in 4K Gaming Monitor               2                 2  
27in FHD Monitor                     4                 4  
34in Ultrawide Monitor               5                 5  
AA Batteries (4-pack)                9                 9  
AAA Batteries (4-pack)              11                11  
Apple Airpods Headphones            10                10  
Bose SoundSport Headphones           4                 4  
Flatscreen TV                        2                 2  
Google Phone                         4                 4  
Lightning Charging Cable            17                17  
Macbook Pro Laptop                   2                 2  
ThinkPad Laptop                      1                 1  
USB-C Charging Cable                14                14  
Vareebadd Phone                      1                 1  
Wired Headphones                     9                 9  
iPhone                               2                 2