In [1]:
import numpy as np
import sympy as sp

In [2]:
u = np.array([2, -2, 3])
v = np.array([1, -3, 4])
w = np.array([3, 6, -4])

In [7]:
np.linalg.norm(v)

5.0990195135927845

### Determinant

In [8]:
np.linalg.det(A)

-0.9999999999999989

### Inverse Matrix

In [9]:
np.linalg.inv(A)

array([[-40.,  16.,   9.],
       [ 13.,  -5.,  -3.],
       [  5.,  -2.,  -1.]])

### RREF

In [11]:
M = sp.Matrix([[1, 1, 2, 9], [2, 4, -3, 1], [3, 6, -5, 0]]) 
M.rref()

(Matrix([
 [1, 0, 0, 1],
 [0, 1, 0, 2],
 [0, 0, 1, 3]]),
 (0, 1, 2))

### 행렬 곱

In [3]:
a = np.array([[1, -2, 0], [4, 1, -3], [5, 2, 4]])
b = np.array([[2, -3, 3], [5, 0, 1], [6, 1, 17]])
np.matmul(a, b)

array([[ 2,  6,  0],
       [20,  0, -3],
       [30,  2, 68]])

### 역행렬

In [16]:
a = np.array([[1, 2, 1], [2, 1, 4], [7, 4, 5]])
np.linalg.inv(a)*np.linalg.det(a)

array([[-11.,  -6.,   7.],
       [ 18.,  -2.,  -2.],
       [  1.,  10.,  -3.]])

### 전치행렬

In [11]:
a.T

array([[ 1,  0],
       [ 3,  1],
       [-1,  1],
       [ 1,  6]])

### Null space

In [6]:
from scipy.linalg import null_space

In [9]:
a = np.array([[1, 3, -1, 1], [0, 1, 1, 6]])
null_space(a)

array([[ 0.10725241, -0.94422357],
       [ 0.33755354,  0.32472351],
       [ 0.91170353, -0.02072024],
       [-0.20820951, -0.05066721]])

### Identity

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Eigen

In [13]:
a = np.array([[1, 0, 3], [0, 2, 3], [0, 0, 4]])
np.linalg.eigvals(a)

array([1., 2., 4.])

In [14]:
np.linalg.eig(a) # eigenvalues, eigenvectors

(array([1., 2., 4.]),
 array([[1.        , 0.        , 0.48507125],
        [0.        , 1.        , 0.72760688],
        [0.        , 0.        , 0.48507125]]))

### Diagonal Entry

In [17]:
a = np.arange(1, 10).reshape(3, 3)
np.diag(a)

array([1, 5, 9])

In [19]:
a = sp.Matrix([[1, 3, -1, 1], [0, 1, 1, 6]])
a.rref()

(Matrix([
 [1, 0, -4, -17],
 [0, 1,  1,   6]]),
 (0, 1))

### Outer product

In [28]:
a = [-2, 1, 4]
b = [1, 3, -2, -1]
np.outer(a, b)

array([[-2, -6,  4,  2],
       [ 1,  3, -2, -1],
       [ 4, 12, -8, -4]])

### Inner product

In [29]:
a = [-2, 1, 4, 100]
b = [1, 3, -2, -1]
np.inner(a, b)

-107

### Rank

In [27]:
a = np.array([[1, 2, -3, 1, 1], [-3, 1, 7, -1, 1],[ -2, 3, 4, 0, 2]])
np.linalg.matrix_rank(a)

2

In [31]:
a = np.array([[1, -1, 2, -1, 1], [4, -3, -1, 1, -2], [3, -2, -3, 2, -3], [6, -5, 3, -1, 0]])
np.linalg.matrix_rank(a.T)

2